services:
  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rpger-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password}@mongodb:27017/rpger?authSource=admin
      - REDIS_URL=redis://:${REDIS_PASSWORD:-password}@redis:6379
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_here}
      - CLIENT_URL=${CLIENT_URL:-http://rpger-frontend:3001}
    ports:
      - "${BACKEND_PORT:-5000}:5000"
      - "5002:5002"
    volumes:
      - ./backend:/app
      - /app/node_modules
    # Note: These services are in the db_stack
    # We're connecting to them via the shared network
    networks:
      - rpger-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rpger-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_URL=http://rpger-backend:5000
      - VITE_SOCKET_URL=http://rpger-backend:5002
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - rpger-network

networks:
  rpger-network:
    name: rpger-network
    external: true
