version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: rpger-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rpger
    networks:
      - rpger-network

  # Redis service
  redis:
    image: redis:latest
    container_name: rpger-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rpger-network

  # MongoDB Express (Web-based MongoDB admin interface)
  mongo-express:
    image: mongo-express:latest
    container_name: rpger-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - rpger-network

  # Redis Commander (Web-based Redis admin interface)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: rpger-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - rpger-network

volumes:
  mongodb_data:
  redis_data:

networks:
  rpger-network:
    driver: bridge
